# Generated by Django 5.0 on 2024-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petstoreapp', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
